language: java

jdk:
  - openjdk8

branches:
  only:
    - development
    - main

before_script:
  - ls -la

script:
  - mvn clean package jacoco:report

after_success:
  - echo "Process terminated successfully."

