language: java

jdk:
  - openjdk8

branches:
  only:
    - development
    - main

before_script:
  - ls -la

script:
  - mvn clean package jacoco:report

after_success:
  - cat `-jar sourcecodeanalyzer/target/sourcecodeanalyzer-0.0.1-SNAPSHOT-jar-with-dependencies.jar sourcecodeanalyzer/src/test/resources/TestClass.java regex local sourcecodeanalyzer/target/metrics_results csv | cut -d " " -f 4`
  - echo "Process terminated successfully."

